name: Check Markdown links
on:
  pull_request:
    paths:
      - '**.md'
permissions:
  contents: read

jobs:
  lint-md:
    runs-on: ubuntu-latest
    if: github.repository == 'DefinitelyTyped/DefinitelyTyped'
    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      - uses: pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d # v3.0.0
        with:
          run_install: |
            - args: [--filter, ., --filter, '{./scripts}...']
      - run: pnpm remark --frail . .github
